### ISSUE TITLE
Search a Specific Field

### ISSUE THREAD

**Issue by sinclr4** [ryan-codingintrigue/Contentful.NET#1]
Hi Ryan, 
Great piece of code, just one question:
Is it possible to search for a specific contenttype and then to search against a specific field to get a match.
e.g Content type of Dog, Gender = Female

Thanks
Rob

**Comment by ryan-codingintrigue** [comment]
Should be possible by adding multiple `EqualitySearchFilter` instances to a `Search`:
```c#
var results = client.SearchAsync<Entry>(cancellationToken, new ISearchFilter[]
{
    new EqualitySearchFilter(BuiltInProperties.ContentType, /* Id of Dog content type */),
    new EqualitySearchFilter("Gender", "Female") // Makes sure that Gender == "Female"
});
```
This would return all Dog content, but only where the Gender = Female.

**Comment by sinclr4** [comment]
Hi Ryan, 
Thanks for this.
I've tried it and it's not quite what I'm after.
The query to Contentful is:
https://cdn.contentful.com/spaces/w4gsrh5e985a/entries?content_type=3kMNZy7VCEc2oW2yy68GyK&fields.topic.sys.id=Medicines&access_token=39426304569b88d9debca37cc08b55f8b08a88415ba518347db824f4a0a75d31

I'm essentially querying based on a link.
Appreciate your help.

Cheers
